### ISSUE TITLE
Electron Support

### ISSUE THREAD

**Issue by anthonym01** [EkoLabs/sonorous#10]
Doesnt seem to work in electron 10.1.4

Get this erroe
App threw an error during load
ReferenceError: window is not defined
    at Object.<anonymous> (D:\Git\Anthonym\node_modules\sonorous\dist\Sonorous.min.js:1:234)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Git\Anthonym\main.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)

Or have i done something wrong?

**Comment by DivyaMahadevan** [comment]
Hey @anthonym01! Happy to take a look- could you provide a gist or a repo that reproduces this issue?
